TIME_STEP = 1 / 40

SEPARATOR = "_"

TEMP_DATA_NAME = "cpp_temp_data"

SHADER_EXTENSION = "glsl"
SHADER_VERTEX = "vert"
SHADER_FRAGMENT = "frag"
SHADER_GEOMETRY = "geom"
SHADER_DEFINES = "def"
SHADER_LIBRARY = "lib"

AUTOCAM_MIN = 0.852
AUTOCAM_MAX = 0.999
