SEPARATOR = "_"

TEMP_DATA_NAME = "cpp_temp_data"

SHADER_EXTENSION = "glsl"
SHADER_VERTEX = "vert"
SHADER_FRAGMENT = "frag"
SHADER_GEOMETRY = "geom"
SHADER_DEFINES = "def"
SHADER_LIBRARY = "lib"

ENSURE_PREVIEWS_INTERVAL = 1.0